services:
  qpanel:
    # build: .
    image: ghcr.io/leo-stotch/qpanel:sha-09d3cd7
    container_name: qpanel
    ports:
      - "${FLASK_PORT:-5001}:5001"
    volumes:
      - qpanel-data:/app/data
      # - /media/downloads/:/downloads:rw
    restart: unless-stopped

volumes:
  qpanel-data:
